coverage:
  status:
    project:
      default:
        informational: true
        target: auto
        threshold: 10%

# Ignoring Paths
# --------------
# which folders/files to ignore
ignore:
  - "**/*_test.go"
  - "**/mock_*.go"