name: my unit tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unittests:
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install mockery
        run: go install github.com/vektra/mockery/v2@v2.20.0

      - name: My unit tests
        run: go test -race -tags fast -coverprofile unit.txt -covermode atomic ./...

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./unit.txt
          name: unit